import { StyleSheet } from 'react-native';

export const GREEN = '#2E7D32';
export const GREEN_TINT = '#E8F5E9';
export const DARK = '#17351D';
export const BG = '#F5FAF5';
export const BORDER = '#C8E6C9';
export const MUTED = '#5f5a74';
export const OK = '#1f8a4c';
export const OK_TINT = '#dff3e6';
export const WARN = '#b7791f';
export const WARN_TINT = '#fdf0d5';
export const BAD = '#c0392b';
export const BAD_TINT = '#fbe3df';

const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: BG },
  container: { padding: 16, paddingBottom: 110 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24 },
  title: { fontSize: 24, fontWeight: 'bold', color: DARK },
  subtitle: { fontSize: 14, color: MUTED, marginTop: 2 },
  muted: { color: MUTED, marginTop: 4 },
  small: { fontSize: 12, color: MUTED, lineHeight: 17, flexShrink: 1 },
  danger: { color: BAD, marginTop: 6 },
  ok: { color: OK, marginTop: 6 },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 6 },
  topBar: {
    backgroundColor: GREEN,
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  topBarTitle: { color: '#fff', fontSize: 18, fontWeight: 'bold', flexShrink: 1, minWidth: 0 },
  topBarSub: { color: '#D9F0DC', fontSize: 12 },
  hero: { backgroundColor: GREEN, borderRadius: 20, padding: 20, marginTop: 8 },
  heroLabel: { color: '#D9F0DC', fontSize: 13 },
  heroValue: { color: '#fff', fontSize: 30, fontWeight: 'bold', marginVertical: 6 },
  row2: { flexDirection: 'row', gap: 12, marginTop: 12 },
  stat: { flex: 1, backgroundColor: '#fff', borderRadius: 16, padding: 14, borderWidth: 1.5, borderColor: BORDER },
  statValue: { fontSize: 18, fontWeight: 'bold', marginTop: 6, color: DARK },
  section: { backgroundColor: '#fff', borderRadius: 18, padding: 16, marginTop: 14, borderWidth: 1.5, borderColor: BORDER },
  heading: { fontSize: 17, fontWeight: 'bold', lineHeight: 22, marginBottom: 10, color: DARK, flexShrink: 1, minWidth: 0 },
  listRow: { paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: BORDER },
  rowBetween: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 8, flexWrap: 'wrap' },
  rowWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, alignItems: 'center' },
  rowTitle: { fontSize: 15, fontWeight: '600', color: DARK, flexShrink: 1, minWidth: 0 },
  label: { fontSize: 13, fontWeight: '600', color: DARK, marginTop: 12, marginBottom: 4 },
  input: {
    backgroundColor: '#fff',
    borderWidth: 1.5,
    borderColor: BORDER,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
    color: DARK,
  },
  inputMulti: { minHeight: 84, textAlignVertical: 'top' },
  pinInput: { textAlign: 'center', fontSize: 24, letterSpacing: 8, alignSelf: 'stretch', marginTop: 16 },
  primary: {
    backgroundColor: GREEN,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
    borderWidth: 1,
    borderColor: GREEN,
  },
  primaryText: { color: '#fff', fontWeight: 'bold', fontSize: 16, lineHeight: 21, textAlign: 'center', flexShrink: 1 },
  buttonFullWidth: { width: '100%', minHeight: 48 },
  buttonInline: { alignSelf: 'flex-start', minHeight: 44, minWidth: 72, maxWidth: '100%', flexShrink: 1 },
  buttonLabel: { textAlign: 'center', flexShrink: 1, flexWrap: 'wrap' },
  secondary: {
    borderWidth: 1.5,
    borderColor: GREEN,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
  },
  secondaryText: { color: GREEN, fontWeight: 'bold', fontSize: 15, lineHeight: 20, textAlign: 'center', flexShrink: 1 },
  dangerBtn: {
    borderWidth: 1.5,
    borderColor: BAD,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
  },
  dangerText: { color: BAD, fontWeight: 'bold', fontSize: 15, lineHeight: 20, textAlign: 'center', flexShrink: 1 },
  disabled: { opacity: 0.5 },
  smallBtn: {
    borderWidth: 1.5,
    borderColor: GREEN,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 7,
    minHeight: 36,
    minWidth: 64,
    maxWidth: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    flexShrink: 1,
  },
  smallBtnText: { color: GREEN, fontWeight: '600', fontSize: 13, lineHeight: 17, textAlign: 'center', flexShrink: 1 },
  chip: {
    borderWidth: 1.5,
    borderColor: BORDER,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 7,
    minHeight: 36,
    maxWidth: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  chipActive: { backgroundColor: GREEN, borderColor: GREEN },
  chipText: { color: DARK, fontWeight: '600', fontSize: 13, lineHeight: 17, textAlign: 'center', flexShrink: 1 },
  chipTextActive: { color: '#fff' },
  badge: { borderRadius: 10, paddingHorizontal: 9, paddingVertical: 3, alignSelf: 'flex-start' },
  badgeText: { fontSize: 12, lineHeight: 16, fontWeight: 'bold', textAlign: 'center', flexShrink: 1 },
  empty: { alignItems: 'center', padding: 28 },
  emptyText: { color: MUTED, textAlign: 'center' },
  nav: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: BORDER,
    paddingBottom: 8,
    paddingTop: 6,
  },
  navItem: { flex: 1, alignItems: 'center', paddingVertical: 4 },
  navText: { fontSize: 11, color: MUTED, marginTop: 2 },
  navTextActive: { fontSize: 11, color: GREEN, fontWeight: 'bold', marginTop: 2 },
  banner: { backgroundColor: WARN_TINT, padding: 10, borderRadius: 10, marginTop: 10 },
  bannerText: { color: WARN, fontSize: 13 },
  toast: { position: 'absolute', left: 16, right: 16, bottom: 90, backgroundColor: DARK, borderRadius: 12, padding: 12 },
  toastText: { color: '#fff', textAlign: 'center' },
  modalWrap: { flex: 1, backgroundColor: 'rgba(13,50,17,0.45)', justifyContent: 'flex-end' },
  modalCard: { backgroundColor: '#fff', borderTopLeftRadius: 22, borderTopRightRadius: 22, padding: 18, maxHeight: '90%' },
  barTrack: { height: 8, backgroundColor: GREEN_TINT, borderRadius: 4, overflow: 'hidden', marginTop: 8 },
  barFill: { height: 8, backgroundColor: GREEN },
});
export default s;
