import type { Data } from '../../../shared/types';
import { DEFAULT_HEADS } from '../../../shared/lib';

export const EMPTY_DATA: Data = {
  months: [],
  payments: [],
  archive: [],
  flats: [],
  settings: {
    hidden: [],
    flatHidden: [],
    custom: [],
    labels: {},
    expenseHeads: DEFAULT_HEADS,
    paymentSplit: 'maint_first',
    orgName: '',
    orgShort: '',
    billing: null,
    serviceContacts: [],
  },
  corpusLedger: [],
  tickets: [],
  hallBookings: [],
  gymBookings: [],
  polls: [],
  events: [],
  authEnabled: true,
  features: {
    auth: true,
    audit: false,
    rateLimit: false,
    reminders: false,
    autoBackup: false,
    mail: false,
    tickets: true,
    hallBooking: true,
    gymBooking: true,
    polls: true,
    events: true,
    notification: false,
  },
  mine: null,
  me: null,
};
